"""fit order to front

Revision ID: 8ad517da0e0c
Revises: 753464417a64
Create Date: 2025-06-07 03:42:35.499932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ad517da0e0c'
down_revision = '753464417a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('customer', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('remark', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['order_id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('item')
        batch_op.drop_column('price')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('item', mysql.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('remark')
        batch_op.drop_column('date')
        batch_op.drop_column('amount')
        batch_op.drop_column('customer')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
